spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/kanbandb_test}
    username: ${SPRING_DATASOURCE_USERNAME:sandboxadmin}
    password: ${SPRING_DATASOURCE_PASSWORD:sandbox@2024}
  flyway:
    enabled: true

jwt:
  secret: test-secret-key-for-unit-tests-only-32c
